name: Build front end
on:
  push:
  pull_request:
  repository_dispatch:
    types: [build]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install javascript dependencies
      run: |
        npm install
    - name: Run build
      run: |
        npm run generate
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
